"""Add audio fields to GeneratedMetadata table

Revision ID: 47c2eca9fc6c
Revises: 9faee399f856
Create Date: 2025-10-04 15:59:05.720229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47c2eca9fc6c'
down_revision: Union[str, Sequence[str], None] = '9faee399f856'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generated_metadata', schema=None) as batch_op:
        batch_op.add_column(sa.Column('audio_introduction_path', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('audio_instructions_path', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generated_metadata', schema=None) as batch_op:
        batch_op.drop_column('audio_instructions_path')
        batch_op.drop_column('audio_introduction_path')

    # ### end Alembic commands ###
