"""Initial migration - create scenarios table

Revision ID: 4c0f3f6518bc
Revises: 
Create Date: 2025-10-04 12:47:24.511550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c0f3f6518bc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scenarios',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('theme', sa.String(length=100), nullable=False),
    sa.Column('difficulty', sa.Enum('EASY', 'MEDIUM', 'HARD', name='difficultylevel'), nullable=False),
    sa.Column('num_players', sa.Integer(), nullable=False),
    sa.Column('estimated_duration', sa.Integer(), nullable=True),
    sa.Column('scenario_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('is_public', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scenarios_difficulty'), 'scenarios', ['difficulty'], unique=False)
    op.create_index(op.f('ix_scenarios_num_players'), 'scenarios', ['num_players'], unique=False)
    op.create_index(op.f('ix_scenarios_theme'), 'scenarios', ['theme'], unique=False)
    op.create_index(op.f('ix_scenarios_title'), 'scenarios', ['title'], unique=False)
    op.create_index(op.f('ix_scenarios_user_id'), 'scenarios', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scenarios_user_id'), table_name='scenarios')
    op.drop_index(op.f('ix_scenarios_title'), table_name='scenarios')
    op.drop_index(op.f('ix_scenarios_theme'), table_name='scenarios')
    op.drop_index(op.f('ix_scenarios_num_players'), table_name='scenarios')
    op.drop_index(op.f('ix_scenarios_difficulty'), table_name='scenarios')
    op.drop_table('scenarios')
    # ### end Alembic commands ###
