"""Add cover_image_path to GeneratedMetadata

Revision ID: 7bc741afef33
Revises: b2f4e80bd0df
Create Date: 2025-10-04 16:40:21.817040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bc741afef33'
down_revision: Union[str, Sequence[str], None] = 'b2f4e80bd0df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generated_metadata', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover_image_path', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generated_metadata', schema=None) as batch_op:
        batch_op.drop_column('cover_image_path')

    # ### end Alembic commands ###
