"""Add language field to games table

Revision ID: 9faee399f856
Revises: 8a8a4a35a747
Create Date: 2025-10-04 15:46:06.377529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9faee399f856'
down_revision: Union[str, Sequence[str], None] = '8a8a4a35a747'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', sa.String(), nullable=False, server_default='en'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_column('language')

    # ### end Alembic commands ###
