"""Remove audio_instructions_path from GeneratedMetadata

Revision ID: b2f4e80bd0df
Revises: 47c2eca9fc6c
Create Date: 2025-10-04 16:18:57.152441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2f4e80bd0df'
down_revision: Union[str, Sequence[str], None] = '47c2eca9fc6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generated_metadata', schema=None) as batch_op:
        batch_op.drop_column('audio_instructions_path')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generated_metadata', schema=None) as batch_op:
        batch_op.add_column(sa.Column('audio_instructions_path', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
