"""Add character_image_path to GeneratedCharacter

Revision ID: b3dcd00315b3
Revises: 7bc741afef33
Create Date: 2025-10-04 17:09:12.072392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3dcd00315b3'
down_revision: Union[str, Sequence[str], None] = '7bc741afef33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generated_characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('character_image_path', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generated_characters', schema=None) as batch_op:
        batch_op.drop_column('character_image_path')

    # ### end Alembic commands ###
